param(
    [Parameter(Mandatory = $true)][string]$ScoExe,
    [Parameter(Mandatory = $true)][string]$Root,
    [Parameter(Mandatory = $true)][string]$GlobalRoot,
    [Parameter(Mandatory = $true)][string]$ConfigHome,
    [Parameter(Mandatory = $true)][string]$BucketSource,
    [Parameter(Mandatory = $true)][string]$Artifact
)

$ErrorActionPreference = 'Stop'

$resolvedRootParent = [System.IO.Path]::GetFullPath((Split-Path -Parent $Root))
if ($resolvedRootParent -notlike '*\build\msvc-release*') {
    throw "Refusing to clean test root outside build tree: $Root"
}

foreach ($path in @($Root, $GlobalRoot, $ConfigHome, $BucketSource)) {
    if (Test-Path $path) {
        Remove-Item -LiteralPath $path -Recurse -Force
    }
}

$sourceBucketDir = Join-Path $BucketSource 'bucket'
New-Item -ItemType Directory -Force -Path $sourceBucketDir | Out-Null

$manifest = [ordered]@{
    version = '1.0.0'
    url = ([System.IO.Path]::GetFullPath($Artifact))
    hash = '5f31429cbc87c555998ed7d20ddb645fd0622c6e9591a4e6e6a329d0f6f4957b'
    bin = 'filetool.exe'
}
$manifest | ConvertTo-Json | Set-Content -Path (Join-Path $sourceBucketDir 'filetool.json') -Encoding UTF8

$depManifest = [ordered]@{
    version = '1.0.0'
    url = ([System.IO.Path]::GetFullPath($Artifact))
    hash = '5f31429cbc87c555998ed7d20ddb645fd0622c6e9591a4e6e6a329d0f6f4957b'
}
$depManifest | ConvertTo-Json | Set-Content -Path (Join-Path $sourceBucketDir 'importdep.json') -Encoding UTF8

$depAppManifest = [ordered]@{
    version = '1.0.0'
    url = ([System.IO.Path]::GetFullPath($Artifact))
    hash = '5f31429cbc87c555998ed7d20ddb645fd0622c6e9591a4e6e6a329d0f6f4957b'
    depends = 'importdep'
}
$depAppManifest | ConvertTo-Json | Set-Content -Path (Join-Path $sourceBucketDir 'importapp.json') -Encoding UTF8

$autoManifest = [ordered]@{
    version = '1.0.0'
    url = ([System.IO.Path]::GetFullPath($Artifact))
    hash = '5f31429cbc87c555998ed7d20ddb645fd0622c6e9591a4e6e6a329d0f6f4957b'
    bin = 'filetool.exe'
    autoupdate = [ordered]@{
        url = ([System.IO.Path]::GetFullPath($Artifact))
        hash = '5f31429cbc87c555998ed7d20ddb645fd0622c6e9591a4e6e6a329d0f6f4957b'
        bin = 'filetool.exe'
    }
}
$autoManifest | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-Path $sourceBucketDir 'autotool.json') -Encoding UTF8

$scoopfile = Join-Path (Split-Path -Parent $Root) 'import-scoopfile.json'
$import = [ordered]@{
    config = [ordered]@{
        'aria2-enabled' = $false
        default_architecture = '32bit'
        use_sqlite_cache = $true
    }
    buckets = @(
        [ordered]@{
            Name = 'main'
            Source = ([System.IO.Path]::GetFullPath($BucketSource))
        }
    )
    apps = @(
        [ordered]@{
            Name = 'filetool'
            Version = '1.0.0'
            Source = 'main'
            Info = 'Held package'
        },
        [ordered]@{
            Name = 'importapp'
            Version = '1.0.0'
            Source = 'main'
            Info = ''
        },
        [ordered]@{
            Name = 'autotool'
            Version = '2.0.0'
            Source = '<auto-generated>'
            Info = '64bit'
        }
    )
}
$import | ConvertTo-Json -Depth 5 | Set-Content -Path $scoopfile -Encoding UTF8

$env:SCOOP = $Root
$env:SCOOP_GLOBAL = $GlobalRoot
$env:XDG_CONFIG_HOME = $ConfigHome
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
$isAdmin = $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

$output = & $ScoExe import $scoopfile
if ($LASTEXITCODE -ne 0) {
    throw "import failed with exit code $LASTEXITCODE`: $output"
}
$joinedOutput = $output -join "`n"
if ($joinedOutput -notmatch "Installing 'filetool' \(1\.0\.0\) \[32bit\] from 'main' bucket" -or $joinedOutput -notmatch "'filetool' \(1\.0\.0\) was installed successfully!") {
    throw "import did not print Scoop-style bucket install output: $joinedOutput"
}
if ($joinedOutput -notmatch "Installing 'importdep' \(1\.0\.0\) \[32bit\] from 'main' bucket" -or
    $joinedOutput -notmatch "Installing 'importapp' \(1\.0\.0\) \[32bit\] from 'main' bucket" -or
    $joinedOutput.IndexOf("Installing 'importdep'") -gt $joinedOutput.IndexOf("Installing 'importapp'")) {
    throw "import did not install dependencies before imported app like normal Scoop install: $joinedOutput"
}
if ($joinedOutput -notmatch "Installing 'autotool' \(2\.0\.0\) \[64bit\] from '.+generated-manifests.+autotool.+2\.0\.0.+autotool\.json'" -or $joinedOutput -notmatch "'autotool' \(2\.0\.0\) was installed successfully!") {
    throw "import did not print Scoop-style generated manifest install output: $joinedOutput"
}
if ($joinedOutput -notmatch 'INFO  Initializing SQLite cache in progress') {
    throw "import did not apply use_sqlite_cache config side effects: $joinedOutput"
}
if ($joinedOutput -notmatch 'INFO  Updating cache') {
    throw "import did not report use_sqlite_cache bucket refresh like Scoop: $joinedOutput"
}

foreach ($path in @(
    (Join-Path $Root 'buckets\main\bucket\filetool.json'),
    (Join-Path $Root 'apps\autotool\2.0.0\filetool.exe'),
    (Join-Path $Root 'apps\importdep\current\filetool.exe'),
    (Join-Path $Root 'apps\importapp\current\filetool.exe'),
    (Join-Path $Root 'apps\filetool\current\filetool.exe'),
    (Join-Path $Root 'shims\filetool.exe'),
    (Join-Path $Root 'shims\filetool.shim')
)) {
    if (!(Test-Path $path)) {
        throw "Missing imported output: $path"
    }
}

$config = Get-Content (Join-Path $ConfigHome 'scoop\config.json') -Raw | ConvertFrom-Json
if ($config.'aria2-enabled' -ne $false) {
    throw "config was not imported: $($config | ConvertTo-Json -Compress)"
}
if ($config.use_sqlite_cache -ne $true) {
    throw "use_sqlite_cache config was not imported: $($config | ConvertTo-Json -Compress)"
}

$indexPath = Join-Path $Root 'cache\buckets.index.json'
if (!(Test-Path $indexPath)) {
    throw "import with use_sqlite_cache did not create bucket manifest index: $indexPath"
}
$index = Get-Content -LiteralPath $indexPath -Raw | ConvertFrom-Json
if (-not ($index.entries | Where-Object { $_.bucket -eq 'main' -and $_.name -eq 'filetool' })) {
    throw "import with use_sqlite_cache did not refresh index after adding buckets: $($index | ConvertTo-Json -Compress)"
}

$autoInstall = Get-Content (Join-Path $Root 'apps\autotool\current\install.json') -Raw | ConvertFrom-Json
if ($autoInstall.architecture -ne '64bit') {
    throw "auto-generated import did not preserve 64bit architecture from Info: $($autoInstall | ConvertTo-Json -Compress)"
}
if ($autoInstall.manifest -notmatch 'generated-manifests.+autotool.+2\.0\.0.+autotool\.json') {
    throw "auto-generated import did not install from generated manifest: $($autoInstall | ConvertTo-Json -Compress)"
}

$install = Get-Content (Join-Path $Root 'apps\filetool\current\install.json') -Raw | ConvertFrom-Json
if ($install.hold -ne $true) {
    throw "hold state was not imported: $($install | ConvertTo-Json -Compress)"
}

$repeatOutput = (& $ScoExe import $scoopfile) -join "`n"
if ($LASTEXITCODE -ne 0) {
    throw "repeat import failed with exit code $LASTEXITCODE`: $repeatOutput"
}
if ($repeatOutput -notmatch "WARN  'filetool' \(1\.0\.0\) is already installed\." -or
    $repeatOutput -notmatch "WARN  Use 'sco update filetool' to install a new version\." -or
    $repeatOutput -notmatch "WARN  'importapp' \(1\.0\.0\) is already installed\." -or
    $repeatOutput -notmatch "WARN  Use 'sco update importapp' to install a new version\." -or
    $repeatOutput -notmatch "WARN  'autotool' \(2\.0\.0\) is already installed\." -or
    $repeatOutput -notmatch "WARN  Use 'sco update autotool' to install a new version\." -or
    $repeatOutput -notmatch "INFO  'filetool' is already held\.") {
    throw "repeat import did not reuse normal single-app install and hold messages: $repeatOutput"
}
if ($repeatOutput -match "Installing 'filetool'" -or
    $repeatOutput -match "Installing 'importapp'" -or
    $repeatOutput -match "Installing 'importdep'" -or
    $repeatOutput -match "Installing 'autotool'" -or
    $repeatOutput -match 'already installed\. Skipping\.') {
    throw "repeat import should not print fresh install or multi-app skipping output for already-installed apps: $repeatOutput"
}

$exported = (& $ScoExe export --config) -join "`n"
if ($LASTEXITCODE -ne 0) {
    throw "export after import failed"
}
$json = $exported | ConvertFrom-Json
if (-not ($json.apps | Where-Object { $_.Name -eq 'filetool' -and $_.Info -match 'Held package' })) {
    throw "export after import did not include held app: $exported"
}
if (-not ($json.apps | Where-Object { $_.Name -eq 'autotool' -and $_.Version -eq '2.0.0' -and $_.Info -match '64bit' })) {
    throw "export after import did not include generated 64bit app: $exported"
}
if (-not ($json.apps | Where-Object { $_.Name -eq 'autotool' -and $_.Source -eq '<auto-generated>' })) {
    throw "export after import did not preserve generated manifest source marker: $exported"
}

$listOutput = (& $ScoExe list) -join "`n"
if ($LASTEXITCODE -ne 0) {
    throw "list after import failed with exit code $LASTEXITCODE`: $listOutput"
}
if ($listOutput -notmatch 'autotool\s+2\.0\.0\s+<auto-generated>') {
    throw "list after import did not show generated manifest source marker like Scoop: $listOutput"
}

$globalImportScoopfile = Join-Path (Split-Path -Parent $Root) 'import-global-scoopfile.json'
$globalImport = [ordered]@{
    buckets = @(
        [ordered]@{
            Name = 'main'
            Source = ([System.IO.Path]::GetFullPath($BucketSource))
        }
    )
    apps = @(
        [ordered]@{
            Name = 'filetool'
            Version = '1.0.0'
            Source = 'main'
            Info = 'Global install'
        }
    )
}
$globalImport | ConvertTo-Json -Depth 5 | Set-Content -Path $globalImportScoopfile -Encoding UTF8

if (Test-Path $Root) {
    Remove-Item -LiteralPath $Root -Recurse -Force
}
if (Test-Path $GlobalRoot) {
    Remove-Item -LiteralPath $GlobalRoot -Recurse -Force
}
$previousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
$globalImportOutput = & $ScoExe import $globalImportScoopfile 2>&1
$globalImportExit = $LASTEXITCODE
$ErrorActionPreference = $previousErrorActionPreference
$globalImportJoined = $globalImportOutput -join "`n"
if ($isAdmin) {
    if ($globalImportExit -ne 0) {
        throw "admin import of global app failed with exit code $globalImportExit`: $globalImportJoined"
    }
    if (!(Test-Path (Join-Path $GlobalRoot 'apps\filetool\current\filetool.exe'))) {
        throw 'admin import of global app did not install into global root'
    }
} else {
    if ($globalImportExit -ne 1) {
        throw "non-admin import of global app returned $globalImportExit instead of 1: $globalImportJoined"
    }
    if ($globalImportJoined -notmatch 'ERROR: you need admin rights to install global apps') {
        throw "non-admin import of global app did not match Scoop install admin error: $globalImportJoined"
    }
    if (Test-Path (Join-Path $GlobalRoot 'apps\filetool')) {
        throw 'non-admin import of global app installed into global root'
    }
}

if (Test-Path $Root) {
    Remove-Item -LiteralPath $Root -Recurse -Force
}
if (Test-Path $ConfigHome) {
    Remove-Item -LiteralPath $ConfigHome -Recurse -Force
}

$extraArgOutput = & $ScoExe import $scoopfile ignored-extra
if ($LASTEXITCODE -ne 0) {
    throw "import with an extra positional argument failed with exit code $LASTEXITCODE`: $extraArgOutput"
}
if (!(Test-Path (Join-Path $Root 'apps\filetool\current\filetool.exe'))) {
    throw 'import did not ignore extra positional arguments like Scoop'
}

if (Test-Path $Root) {
    Remove-Item -LiteralPath $Root -Recurse -Force
}
if (Test-Path $ConfigHome) {
    Remove-Item -LiteralPath $ConfigHome -Recurse -Force
}

$listenerPrefix = 'http://127.0.0.1:18189/'
$job = Start-Job -ScriptBlock {
    param($Prefix, $File)
    $listener = [System.Net.HttpListener]::new()
    $listener.Prefixes.Add($Prefix)
    $listener.Start()
    try {
        $context = $listener.GetContext()
        $bytes = [System.IO.File]::ReadAllBytes($File)
        $context.Response.StatusCode = 200
        $context.Response.ContentType = 'application/json'
        $context.Response.ContentLength64 = $bytes.Length
        $context.Response.OutputStream.Write($bytes, 0, $bytes.Length)
        $context.Response.OutputStream.Close()
    } finally {
        $listener.Stop()
        $listener.Close()
    }
} -ArgumentList $listenerPrefix, $scoopfile

Start-Sleep -Milliseconds 300
try {
    $urlOutput = & $ScoExe import ($listenerPrefix + 'scoopfile.json')
    if ($LASTEXITCODE -ne 0) {
        throw "import from URL failed with exit code $LASTEXITCODE`: $urlOutput"
    }
} finally {
    Wait-Job $job -Timeout 5 | Out-Null
    Receive-Job $job | Out-Null
    Remove-Job $job -Force
}

foreach ($path in @(
    (Join-Path $Root 'buckets\main\bucket\filetool.json'),
    (Join-Path $Root 'apps\autotool\2.0.0\filetool.exe'),
    (Join-Path $Root 'apps\filetool\current\filetool.exe'),
    (Join-Path $Root 'shims\filetool.exe'),
    (Join-Path $Root 'shims\filetool.shim')
)) {
    if (!(Test-Path $path)) {
        throw "Missing URL imported output: $path"
    }
}

if (Test-Path $Root) {
    Remove-Item -LiteralPath $Root -Recurse -Force
}
if (Test-Path $ConfigHome) {
    Remove-Item -LiteralPath $ConfigHome -Recurse -Force
}

$arm64SqliteScoopfile = Join-Path (Split-Path -Parent $Root) 'import-arm64-sqlite-scoopfile.json'
[ordered]@{
    config = [ordered]@{
        default_architecture = 'arm64'
        use_sqlite_cache = $true
    }
} | ConvertTo-Json -Depth 4 | Set-Content -Path $arm64SqliteScoopfile -Encoding UTF8

$previousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
$arm64SqliteOutput = & $ScoExe import $arm64SqliteScoopfile 2>&1
$arm64SqliteExit = $LASTEXITCODE
$ErrorActionPreference = $previousErrorActionPreference
if ($arm64SqliteExit -ne 1) {
    throw "import with arm64 default architecture and use_sqlite_cache returned $arm64SqliteExit instead of 1: $arm64SqliteOutput"
}
if (($arm64SqliteOutput -join "`n") -notmatch 'SQLite cache is not supported on ARM64 platform') {
    throw "import with arm64 default architecture and use_sqlite_cache did not match Scoop error: $arm64SqliteOutput"
}
if (Test-Path (Join-Path $ConfigHome 'scoop\config.json')) {
    throw 'failed import with arm64 sqlite cache should not save partial config'
}
