name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: lukka/run-vcpkg@v11

      - name: Configure
        run: >
          cmake -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DVCPKG_TARGET_TRIPLET=x64-windows-static-md
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/sco.exe
