name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git "$env:RUNNER_TEMP\vcpkg"
          & "$env:RUNNER_TEMP\vcpkg\bootstrap-vcpkg.bat" -disableMetrics
          echo "VCPKG_ROOT=$env:RUNNER_TEMP\vcpkg" >> $env:GITHUB_ENV

      - name: Configure
        run: >
          cmake -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DVCPKG_TARGET_TRIPLET=x64-windows-static-md
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/sco.exe
